# Generated by Django 5.1.3 on 2024-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='Изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
